<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard Report - <?= date('Y-m-d') ?></title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 20px;
            color: #333;
        }
        .print-header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
        }
        .print-header h1 {
            margin: 0;
            color: #0f2823;
        }
        .print-header .date {
            color: #666;
            margin-top: 5px;
        }
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 20px;
            margin-bottom: 40px;
        }
        .stat-card {
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 20px;
            text-align: center;
        }
        .stat-card h2 {
            margin: 10px 0;
            color: #0f2823;
        }
        .stat-card .label {
            color: #666;
            font-size: 14px;
        }
        .data-section {
            margin: 40px 0;
        }
        .data-section h3 {
            color: #0f2823;
            border-bottom: 1px solid #ddd;
            padding-bottom: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        table th, table td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }
        table th {
            background-color: #f8f9fa;
            color: #0f2823;
        }
        .print-footer {
            text-align: center;
            margin-top: 50px;
            color: #666;
            font-size: 12px;
            border-top: 1px solid #ddd;
            padding-top: 20px;
        }
        @media print {
            .no-print {
                display: none;
            }
            body {
                padding: 0;
            }
        }
    </style>
</head>
<body>
    <div class="print-header">
        <h1>Dashboard Summary Report</h1>
        <div class="date">Generated on: <?= date('F j, Y \a\t H:i:s') ?></div>
    </div>

    <div class="stats-grid">
        <div class="stat-card">
            <div class="label">Total Rings in Collection</div>
            <h2><?= $total_rings ?></h2>
        </div>
        <div class="stat-card">
            <div class="label">Active Orders (Paid)</div>
            <h2><?= $active_reservations ?></h2>
        </div>
        <div class="stat-card">
            <div class="label">Pending Approvals</div>
            <h2><?= $pending_reservations ?></h2>
        </div>
    </div>

    <div class="data-section">
        <h3>Recent Rings (First 10)</h3>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Material</th>
                    <th>Price</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($rings_list as $ring): ?>
                <tr>
                    <td><?= $ring['id'] ?></td>
                    <td><?= htmlspecialchars($ring['name']) ?></td>
                    <td><?= htmlspecialchars($ring['material']) ?></td>
                    <td>$<?= number_format($ring['price'], 2) ?></td>
                    <td><?= ucfirst($ring['status']) ?></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <div class="data-section">
        <h3>Recent Reservations (First 10)</h3>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>User ID</th>
                    <th>Ring ID</th>
                    <th>Total Amount</th>
                    <th>Status</th>
                    <th>Created At</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($reservations_list as $res): ?>
                <tr>
                    <td><?= $res['id'] ?></td>
                    <td><?= $res['user_id'] ?></td>
                    <td><?= $res['ring_id'] ?></td>
                    <td>$<?= number_format($res['total_amount'], 2) ?></td>
                    <td><?= ucfirst($res['status']) ?></td>
                    <td><?= date('M j, Y', strtotime($res['created_at'])) ?></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <div class="print-footer">
        <p>Report generated by Jewelry Management System</p>
        <p>Page 1 of 1</p>
    </div>

    <script>
        // Auto-print when the page loads
        window.onload = function() {
            window.print();
        }
    </script>
</body>
</html>